/* Copyright (c) 2014 Freescale Semiconductor, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Freescale Semiconductor nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 *
 * ALTERNATIVELY, this software may be distributed under the terms of the
 * GNU General Public License ("GPL") as published by the Free Software
 * Foundation, either version 2 of that License or (at your option) any
 * later version.
 *
 * THIS SOFTWARE IS PROVIDED BY Freescale Semiconductor ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL Freescale Semiconductor BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <compat.h>
#include <fsl_qman.h>
#include <stdio.h>
#include <capwap_debug.h>

//extern int32_t g_key_split_flag;

/*
 * brief Enqueue Rejection Notification Handler for SEC Tx FQ
 * param[in] msg Message Ring entry to be processed
 * param[out] NULL
 */
static void capwap_ern_handler(struct qman_portal *qm, struct qman_fq *fq,
			const struct qm_mr_entry *msg)
{
	fprintf(stderr, "error: %s: RC = %x, seqnum = %x\n", __func__,
		msg->ern.rc, msg->ern.seqnum);
	return;
}
#if 0
/*
 * brief Handler for Split Key generated by SEC Block
 */
static enum qman_cb_dqrr_result dqrr_split_key_handler(struct qman_portal *qm,
					struct qman_fq *fq,
					const struct qm_dqrr_entry *dqrr)
{
	if(dqrr->fd.status)
		printf("Error for Split-Key genetator, fqid=0x%x\tfd_status ="
				"0x%08x\n", fq->fqid, dqrr->fd.status);
	else
		g_key_split_flag = 1;
	return qman_cb_dqrr_consume;
}
#endif
/*
 * brief Handler for Split Key generated by SEC Block
 */
static enum qman_cb_dqrr_result dqrr_capwap_handler(struct qman_portal *qm,
					struct qman_fq *fq,
					const struct qm_dqrr_entry *dqrr)
{
	return qman_cb_dqrr_consume;
}

/*
 * brief Dummy function for unsupported handlers
 */
static void my_cb_notimplemented(struct qman_portal *qm, struct qman_fq *fq,
			const struct qm_mr_entry *msg)
{
}

const struct qman_fq_cb capwap_tx_cb = {
	.dqrr = dqrr_capwap_handler,
	.ern = capwap_ern_handler,
	.fqs = my_cb_notimplemented
};
#if 0
/*
 * brief Handler for SEC Generated Split Key
 */
const struct qman_fq_cb capwap_split_key_cb = {
	.dqrr = dqrr_split_key_handler,
	.ern = my_cb_notimplemented,
	.fqs = my_cb_notimplemented
};
#endif
